## Assignment 2 by Tyler Trotter
### Numpy and Pandas

In [5]:
# if you do not have numpy and pandas installed, first do so with:
# pip install numpy
# pip install pandas
# or, if you are using conda:
# conda install numpy
# conda install pandas
import numpy as np
import pandas as pd

In [6]:
# convert the lists to numpy arrays and add the elements respectively
list_1 = [1, 2, 3, 4, 5]
list_2 = [22, 71, 14, 0, 45]

np_list_1 = np.array(list_1)
np_list_2 = np.array(list_2)

print(np_list_1 + np_list_2)

[23 73 17  4 50]


In [7]:
# what other operations can you do with these numpy arrays?
np_list_1 * np_list_2
np_list_1 / np_list_2
np_list_1 - np_list_2

C:\Users\Tyler\AppData\Local\Temp\ipykernel_8768\479455230.py:3: RuntimeWarning: divide by zero encountered in divide
  np_list_1 / np_list_2


array([-21, -69, -11,   4, -40])

In [8]:
# convert the elements of one of the arrays to floats

float_np_list_1 = np_list_1.astype(np.float32)

In [9]:
# find the sum and mean of the elements of list_2

sum = np.sum(np_list_2)
print(sum)

mean = np.mean(np_list_2)
print(mean)

152
30.4


In [10]:
# make a numpy array of all integers from 1 to 100 and turn it into a 10x10 square array

int_list = np.arange(1, 101)
int_matrix = int_list.reshape(10,10)
print(int_matrix)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


In [11]:
# multiply the 10x10 array with itself using component-wise multiplication

int_matrix ** 2

array([[    1,     4,     9,    16,    25,    36,    49,    64,    81,
          100],
       [  121,   144,   169,   196,   225,   256,   289,   324,   361,
          400],
       [  441,   484,   529,   576,   625,   676,   729,   784,   841,
          900],
       [  961,  1024,  1089,  1156,  1225,  1296,  1369,  1444,  1521,
         1600],
       [ 1681,  1764,  1849,  1936,  2025,  2116,  2209,  2304,  2401,
         2500],
       [ 2601,  2704,  2809,  2916,  3025,  3136,  3249,  3364,  3481,
         3600],
       [ 3721,  3844,  3969,  4096,  4225,  4356,  4489,  4624,  4761,
         4900],
       [ 5041,  5184,  5329,  5476,  5625,  5776,  5929,  6084,  6241,
         6400],
       [ 6561,  6724,  6889,  7056,  7225,  7396,  7569,  7744,  7921,
         8100],
       [ 8281,  8464,  8649,  8836,  9025,  9216,  9409,  9604,  9801,
        10000]])

In [12]:
# multiply the 10x10 array with itself using standard matrix multiplication

int_matrix.dot(int_matrix)

array([[ 3355,  3410,  3465,  3520,  3575,  3630,  3685,  3740,  3795,
         3850],
       [ 7955,  8110,  8265,  8420,  8575,  8730,  8885,  9040,  9195,
         9350],
       [12555, 12810, 13065, 13320, 13575, 13830, 14085, 14340, 14595,
        14850],
       [17155, 17510, 17865, 18220, 18575, 18930, 19285, 19640, 19995,
        20350],
       [21755, 22210, 22665, 23120, 23575, 24030, 24485, 24940, 25395,
        25850],
       [26355, 26910, 27465, 28020, 28575, 29130, 29685, 30240, 30795,
        31350],
       [30955, 31610, 32265, 32920, 33575, 34230, 34885, 35540, 36195,
        36850],
       [35555, 36310, 37065, 37820, 38575, 39330, 40085, 40840, 41595,
        42350],
       [40155, 41010, 41865, 42720, 43575, 44430, 45285, 46140, 46995,
        47850],
       [44755, 45710, 46665, 47620, 48575, 49530, 50485, 51440, 52395,
        53350]])

In [13]:
# create three arrays of length 100 of random numbers of any distribution you choose

one = np.random.uniform(size = 100)
two = np.random.normal(0, 1, 100)
three = np.random.exponential(1, 100)

In [14]:
# create a pandas DataFrame with the arrays you just created as columns
# set the names of the columns to X1, X2, and X3
d = {'X1': one, 'X2': two, 'X3': three}
data = pd.DataFrame(d)
print(data)

          X1        X2        X3
0   0.147943 -0.479872  0.060763
1   0.503083  0.246431  0.138136
2   0.489665 -0.209323  0.026915
3   0.821686 -0.171721  2.088890
4   0.756637 -0.830522  1.100243
..       ...       ...       ...
95  0.369457 -1.581431  1.887972
96  0.559470  0.249174  0.096212
97  0.403096 -0.394140  2.229102
98  0.882303 -0.338805  0.182894
99  0.887394  0.428502  0.023216

[100 rows x 3 columns]


In [15]:
# calculate the mean of all columns of the data frame at once

col_means = data.mean()
print(col_means)

X1    0.532885
X2    0.108645
X3    0.873832
dtype: float64


In [16]:
# do the same with the sum, and the standard deviation

col_sums = data.sum()
print("Sums: ")
print(col_sums)
col_std = data.std()
print("\nStandard Deviations: ")
print(col_std)


Sums: 
X1    53.288486
X2    10.864524
X3    87.383150
dtype: float64

Standard Deviations: 
X1    0.282875
X2    1.041871
X3    0.849588
dtype: float64


In [17]:
# use the describe method to see all key statistical summaries of all the columns of the data frame

data.describe()

X1          X2          X3
count  100.000000  100.000000  100.000000
mean     0.532885    0.108645    0.873832
std      0.282875    1.041871    0.849588
min      0.015335   -2.673979    0.004459
25%      0.324035   -0.630233    0.264305
50%      0.550879    0.076817    0.546840
75%      0.753532    0.879572    1.193240
max      0.998823    2.698555    4.357985

In [18]:
# create a new column X4 which is in some way a combination of any of the first three columns
data['X4'] = data['X1']*data['X3'] - data['X2']
print(data)

          X1        X2        X3        X4
0   0.147943 -0.479872  0.060763  0.488861
1   0.503083  0.246431  0.138136 -0.176937
2   0.489665 -0.209323  0.026915  0.222503
3   0.821686 -0.171721  2.088890  1.888133
4   0.756637 -0.830522  1.100243  1.663006
..       ...       ...       ...       ...
95  0.369457 -1.581431  1.887972  2.278955
96  0.559470  0.249174  0.096212 -0.195346
97  0.403096 -0.394140  2.229102  1.292681
98  0.882303 -0.338805  0.182894  0.500173
99  0.887394  0.428502  0.023216 -0.407900

[100 rows x 4 columns]


In [19]:
# What else can you do with your data frame?

print("https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.isin.html \n")

data.isin([0.333])

https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.isin.html 



X1     X2     X3     X4
0   False  False  False  False
1   False  False  False  False
2   False  False  False  False
3   False  False  False  False
4   False  False  False  False
..    ...    ...    ...    ...
95  False  False  False  False
96  False  False  False  False
97  False  False  False  False
98  False  False  False  False
99  False  False  False  False

[100 rows x 4 columns]